Add form for lab page
codex-team/codex pull request #615
Opened 2021-06-01 15:44 UTC by talyguryn

![image](https://user-images.githubusercontent.com/15259299/120352336-59952280-c309-11eb-8612-3c876f738ac0.png)

2021-06-02 11:21 UTC, n0str approved these changes

2021-06-02 11:21 UTC, n0str commented on www/application/classes/Controller/Pages.php
> +//        if ($this->user->getUserRequest()) {
what is it?

2021-06-21 17:09 UTC, neSpecc commented
Добавьте нормальное описание реквеста плз. Что изменилось, зачем, где тестить.

2021-06-21 17:12 UTC, neSpecc requested changes

2021-06-21 17:12 UTC, neSpecc commented on www/application/views/templates/blocks/form-join.php
> +<? if ( !$request || True ): ?>
PR точно готов к ревью?

2021-07-27 17:42 UTC, neSpecc approved these changes

2021-07-27 17:43 UTC, merged